#!/usr/bin/env php
<?php
// rollout
require __DIR__ . '/vendor/autoload.php';

use Rollout\Command\DeployCommand;
use Symfony\Component\Console\Application;
use Rollout\Service\ConfigService;
use Rollout\Service\AuthService;
use Rollout\Command\RegisterCommand;
use Rollout\Command\LoginCommand;
use Rollout\Command\WhoamiCommand;
use Rollout\Service\ApiClientService;

$configService = new ConfigService;
$authService = new AuthService($configService);
$apiClientService = new ApiClientService($configService);

$application = new Application;
$application->add(new RegisterCommand($configService, $apiClientService));
$application->add(new LoginCommand($configService, $apiClientService));
$application->add(new DeployCommand($configService, $apiClientService));
$application->add(new WhoamiCommand($configService, $apiClientService));
$application->setDefaultCommand('deploy');

$application->run();
